language: node_js
cache:
  directories:
    - ~/.npm
jobs:
  include:
    - stage: test
      script:
        - npm run webpack-production
        - npm run lint
        - npm run test
      after_success:
        - npm run codecov
    - stage: deploy
      if: branch = master
      script: npm run semantic-release
